# Generated by Django 6.1 on 2026-08-14 22:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vaultmember',
            unique_together={('vault_id', 'member_id')},
        ),
    ]
