# Generated by Django 6.1 on 2026-08-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_alter_vaultmember_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vault',
            options={},
        ),
        migrations.AddField(
            model_name='vaultmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=7),
        ),
    ]
