# Generated by Django 6.1 on 2026-08-25 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_alter_vault_options_vaultmember_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('expiration_date', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='vault',
            name='members',
            field=models.ManyToManyField(related_name='vaults', through='vault.VaultMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='QuantitiveItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vault.item')),
                ('count', models.PositiveIntegerField()),
            ],
            bases=('vault.item',),
        ),
        migrations.AddField(
            model_name='item',
            name='vault_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.vault'),
        ),
    ]
