# Generated by Django 6.1 on 2026-08-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_username_user_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='User Name'),
        ),
    ]
